In [108]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

pd.options.display.float_format = '{:20,.2f}'.format # suprimimos la notacion cientifica en los outputs
plt.style.use('default') # haciendo los graficos un poco mas bonitos en matplotlib
#plt.rcParams['figure.figsize'] = (20, 10)

sns.set(style="whitegrid") # seteando tipo de grid en seaborn

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [109]:
airline_data = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/airline_data.csv", parse_dates = ["date"])
cleaned_reviews = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/cleaned-reviews.csv", parse_dates = ["date"]) # todos los que no opinaron se filtraron ????/
costumer_data = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/customer_airways_data.csv", encoding = "iso-8859-1")
costumer_data_filtrada = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/filtered_customer_booking.csv")

In [178]:
preferencias = costumer_data.iloc[:,8:12]
preferencias = preferencias.rename(columns={"booking_origin": "country"})

In [127]:

def corregir_rates(serie):
  if(serie == "None"):
    return -1
  elif(serie == "\n\t\t\t\t\t\t\t\t\t\t\t\t\t5"):
    return 5
  else:
    return serie

airline_data["rates"] = airline_data["rates"].map(corregir_rates)
airline_data.rates = airline_data.rates.astype(np.int8)

In [169]:
datos_filtrados = airline_data.iloc[:,[2,4]]
datos_filtrados

      rates         country
0         5  United Kingdom
1         9  United Kingdom
2         9  United Kingdom
3         9  United Kingdom
4         2   United States
...     ...             ...
3413      6       Australia
3414     10  United Kingdom
3415      1  United Kingdom
3416      4  United Kingdom
3417      2  United Kingdom

[3418 rows x 2 columns]

In [187]:

preferencias_paises = pd.merge(datos_filtrados,preferencias,how = "outer")
promedios_altos =preferencias_paises[ preferencias_paises.rates > 8 ]#consideramos que 9 es un puntaje alto
promedios_altos_filtrados = promedios_altos.dropna()
promedios_altos_filtrados

,rates,country,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals
173,9.00,United Kingdom,1.00,1.00,1.00
174,9.00,United Kingdom,1.00,0.00,1.00
175,9.00,United Kingdom,0.00,0.00,0.00
176,9.00,United Kingdom,1.00,0.00,1.00
177,9.00,United Kingdom,0.00,0.00,0.00
...,...,...,...,...,...
3472183,9.00,Turkey,0.00,0.00,0.00
3472184,9.00,Turkey,0.00,0.00,0.00
3472185,9.00,Turkey,1.00,0.00,1.00
3472186,9.00,Turkey,1.00,0.00,1.00
3472187,9.00,Turkey,1.00,0.00,0.00

In [191]:
promedios_altos_filtrados.sort_values("rates",ascending=False)

,rates,country,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals
1583051,10.00,Australia,1.00,0.00,0.00
2811951,10.00,Australia,1.00,0.00,1.00
2811981,10.00,Australia,1.00,1.00,1.00
2811980,10.00,Australia,1.00,1.00,1.00
2811979,10.00,Australia,1.00,0.00,1.00
...,...,...,...,...,...
1010723,9.00,Australia,1.00,0.00,1.00
1010722,9.00,Australia,1.00,1.00,1.00
1010721,9.00,Australia,1.00,1.00,1.00
1010720,9.00,Australia,1.00,0.00,0.00
3472187,9.00,Turkey,1.00,0.00,0.00

In [197]:
promedios_altos_filtrados = promedios_altos_filtrados.pivot_table(index="country",columns=["wants_extra_baggage","wants_preferred_seat","wants_in_flight_meals"],values="rates")
promedios_altos_filtrados

wants_extra_baggage                   0.00                       \
wants_preferred_seat                  0.00
wants_in_flight_meals                 0.00                 1.00
country
Argentina                             9.67                  NaN
Australia                             9.38                 9.38
Austria                               9.50                 9.50
Belgium                               9.75                  NaN
Brazil                                9.00                 9.00
Bulgaria                               NaN                  NaN
Canada                                9.42                 9.42
China                                 9.00                 9.00
Denmark                               9.33                 9.33
France                                9.40                 9.40
Germany                               9.60                 9.60
Ghana                                  NaN                  NaN
Greece                                 NaN                  NaN
Hong Kong                             9.60                 9.60
India                                 9.00                 9.00
Ireland                               9.50                 9.50
Italy                                 9.50                 9.50
Laos                                 10.00                10.00
Malaysia                             10.00                10.00
Netherlands                           9.71                 9.71
New Zealand                          10.00                10.00
Portugal                              9.00                  NaN
Qatar                                 9.50                 9.50
Romania                                NaN                 9.00
Saudi Arabia                          9.00                 9.00
Singapore                             9.50                 9.50
South Africa                          9.50                 9.50
Spain                                 9.25                 9.25
Sweden                                9.50                 9.50
Switzerland                           9.62                  NaN
Taiwan                                9.00                 9.00
Thailand                              9.33                 9.33
Turkey                                9.00                 9.00
United Arab Emirates                  9.50                 9.50
United Kingdom                        9.51                 9.51
United States                         9.58                 9.58

wants_extra_baggage                                              \
wants_preferred_seat                  1.00
wants_in_flight_meals                 0.00                 1.00
country
Argentina                             9.67                  NaN
Australia                             9.38                 9.38
Austria                                NaN                  NaN
Belgium                                NaN                  NaN
Brazil                                9.00                  NaN
Bulgaria                               NaN                  NaN
Canada                                9.42                 9.42
China                                 9.00                 9.00
Denmark                                NaN                 9.33
France                                9.40                 9.40
Germany                               9.60                 9.60
Ghana                                  NaN                  NaN
Greece                                 NaN                  NaN
Hong Kong                             9.60                 9.60
India                                 9.00                 9.00
Ireland                                NaN                  NaN
Italy                                 9.50                  NaN
Laos                                   NaN                  NaN
Malaysia                             10.00                10.00
Netherlands                           9.71                 9.71
New Zealand                          10.00                10.00
Portugal                               NaN                  NaN
Qatar                                  NaN                  NaN
Romania                                NaN                  NaN
Saudi Arabia                           NaN                 9.00
Singapore                             9.50                 9.50
South Africa                           NaN                  NaN
Spain                                 9.25                  NaN
Sweden                                 NaN                  NaN
Switzerland                           9.62                  NaN
Taiwan                                9.00                 9.00
Thailand                              9.33                 9.33
Turkey                                9.00                  NaN
United Arab Emirates                  9.50                 9.50
United Kingdom                        9.51                 9.51
United States                         9.58                 9.58

wants_extra_baggage                   1.00                       \
wants_preferred_seat                  0.00
wants_in_flight_meals                 0.00                 1.00
country
Argentina                             9.67                  NaN
Australia                             9.38                 9.38
Austria                               9.50                 9.50
Belgium                               9.75                 9.75
Brazil                                9.00                  NaN
Bulgaria                             10.00                  NaN
Canada                                9.42                 9.42
China                                 9.00                 9.00
Denmark                               9.33                  NaN
France                                9.40                 9.40
Germany                               9.60                 9.60
Ghana                                  NaN                  NaN
Greece                               10.00                  NaN
Hong Kong                             9.60                 9.60
India                                 9.00                 9.00
Ireland                                NaN                 9.50
Italy                                 9.50                 9.50
Laos                                 10.00                10.00
Malaysia                             10.00                10.00
Netherlands                           9.71                 9.71
New Zealand                          10.00                10.00
Portugal                              9.00                 9.00
Qatar                                 9.50                 9.50
Romania                                NaN                 9.00
Saudi Arabia                          9.00                 9.00
Singapore                             9.50                 9.50
South Africa                          9.50                  NaN
Spain                                 9.25                 9.25
Sweden                                9.50                 9.50
Switzerland                           9.62                 9.62
Taiwan                                9.00                 9.00
Thailand                              9.33                 9.33
Turkey                                9.00                 9.00
United Arab Emirates                  9.50                 9.50
United Kingdom                        9.51                 9.51
United States                         9.58                 9.58

wants_extra_baggage
wants_preferred_seat                  1.00
wants_in_flight_meals                 0.00                 1.00
country
Argentina                              NaN                  NaN
Australia                             9.38                 9.38
Austria                                NaN                 9.50
Belgium                               9.75                 9.75
Brazil                                 NaN                 9.00
Bulgaria                               NaN                  NaN
Canada                                9.42                 9.42
China                                 9.00                 9.00
Denmark                               9.33                  NaN
France                                9.40                 9.40
Germany                               9.60                 9.60
Ghana                                  NaN                10.00
Greece                                 NaN                10.00
Hong Kong                             9.60                 9.60
India                                 9.00                 9.00
Ireland                                NaN                 9.50
Italy                                 9.50                 9.50
Laos                                 10.00                10.00
Malaysia                             10.00                10.00
Netherlands                           9.71                 9.71
New Zealand                          10.00                10.00
Portugal                               NaN                 9.00
Qatar                                  NaN                 9.50
Romania                                NaN                 9.00
Saudi Arabia                          9.00                 9.00
Singapore                             9.50                 9.50
South Africa                           NaN                  NaN
Spain                                 9.25                 9.25
Sweden                                 NaN                 9.50
Switzerland                           9.62                 9.62
Taiwan                                9.00                 9.00
Thailand                              9.33                 9.33
Turkey                                 NaN                  NaN
United Arab Emirates                  9.50                 9.50
United Kingdom                        9.51                 9.51
United States                         9.58                 9.58