In [52]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

pd.options.display.float_format = '{:20,.2f}'.format # suprimimos la notacion cientifica en los outputs
plt.style.use('default') # haciendo los graficos un poco mas bonitos en matplotlib
#plt.rcParams['figure.figsize'] = (20, 10)

sns.set(style="whitegrid") # seteando tipo de grid en seaborn

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [53]:
airline_data = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/airline_data.csv", parse_dates = ["date"])
cleaned_reviews = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/cleaned-reviews.csv", parse_dates = ["date"]) # todos los que no opinaron se filtraron ????/
costumer_data = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/customer_airways_data.csv", encoding = "iso-8859-1")
costumer_data_filtrada = pd.read_csv("/content/drive/MyDrive/tp1- orga de datos/Datos clientes/filtered_customer_booking.csv")

In [54]:

costumer_data

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,2,Internet,RoundTrip,262,19,7,Sat,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,Internet,RoundTrip,112,20,3,Sat,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,Internet,RoundTrip,243,22,17,Wed,AKLDEL,India,1,1,0,5.52,0
3,1,Internet,RoundTrip,96,31,4,Sat,AKLDEL,New Zealand,0,0,1,5.52,0
4,2,Internet,RoundTrip,68,22,15,Wed,AKLDEL,India,1,0,1,5.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2,Internet,RoundTrip,27,6,9,Sat,PERPNH,Australia,1,0,1,5.62,0
49996,1,Internet,RoundTrip,111,6,4,Sun,PERPNH,Australia,0,0,0,5.62,0
49997,1,Internet,RoundTrip,24,6,22,Sat,PERPNH,Australia,0,0,1,5.62,0
49998,1,Internet,RoundTrip,15,6,11,Mon,PERPNH,Australia,1,0,1,5.62,0
49999,1,Internet,RoundTrip,19,6,10,Thu,PERPNH,Australia,0,1,0,5.62,0

In [63]:
preferencias = costumer_data.iloc[:,9:12]
preferencias

       wants_extra_baggage  wants_preferred_seat  wants_in_flight_meals
0                        1                     0                      0
1                        0                     0                      0
2                        1                     1                      0
3                        0                     0                      1
4                        1                     0                      1
...                    ...                   ...                    ...
49995                    1                     0                      1
49996                    0                     0                      0
49997                    0                     0                      1
49998                    1                     0                      1
49999                    0                     1                      0

[50000 rows x 3 columns]

In [56]:
airline_data

,Unnamed: 0,reviews,rates,date,country
0,0,✅ Trip Verified | Excellent service both on th...,\n\t\t\t\t\t\t\t\t\t\t\t\t\t5,2023-01-24,United Kingdom
1,1,✅ Trip Verified | Good lounge at Cape Town. O...,9,2023-01-24,United Kingdom
2,2,✅ Trip Verified | A really excellent journey....,9,2023-01-23,United Kingdom
3,3,✅ Trip Verified | This flight was one of the ...,9,2023-01-21,United Kingdom
4,4,Not Verified | It seems that there is a race t...,2,2023-01-19,United States
...,...,...,...,...,...
3413,3413,Flew British Airways from Sydney to Venice on ...,6,2014-05-20,Australia
3414,3414,Recently for our honeymoon we took advantage o...,10,2014-05-19,United Kingdom
3415,3415,LGW-Antigua on 29 April and Antigua-LGW on 13 ...,1,2014-05-18,United Kingdom
3416,3416,LHR-JTR-LHR. A tale of opposites for BA's new ...,4,2014-05-18,United Kingdom
3417,3417,Gatwick-Venice return. Two contrasting experie...,2,2014-05-18,United Kingdom

In [70]:
datos_filtrados = airline_data.iloc[:,2:]
datos_filtrados.iloc[0,0] = 5
def corregir_rates(serie):
  if(serie == "None"):
    return -1

In [72]:
vuelos_y_preferencias = pd.concat([datos_filtrados,preferencias])
vuelos_y_preferencias

,rates,date,country,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals
0,5,2023-01-24,United Kingdom,NaN,NaN,NaN
1,9,2023-01-24,United Kingdom,NaN,NaN,NaN
2,9,2023-01-23,United Kingdom,NaN,NaN,NaN
3,9,2023-01-21,United Kingdom,NaN,NaN,NaN
4,2,2023-01-19,United States,NaN,NaN,NaN
...,...,...,...,...,...,...
49995,NaN,NaT,NaN,1.00,0.00,1.00
49996,NaN,NaT,NaN,0.00,0.00,0.00
49997,NaN,NaT,NaN,0.00,0.00,1.00
49998,NaN,NaT,NaN,1.00,0.00,1.00
49999,NaN,NaT,NaN,0.00,1.00,0.00

In [86]:
vuelos_y_preferencias.fillna(-1)
vuelos_y_preferencias.iloc[ 2915,0] = -1
vuelos_y_preferencias.iloc[3048 ,0] = -1
puntaje = pd.to_numeric(vuelos_y_preferencias.rates)

#vuelos_y_preferencias["rates"].astype(int)

ValueError: Unable to parse string "None" at position 3067

In [84]:
puntaje = pd.to_numeric(vuelos_y_preferencias.rates)

ValueError: Unable to parse string "None" at position 3048